version: "3"

services:
  react-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: "react-app"
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.react-app.rule=Host(`demeureinsolite.fr`)"
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls=true"
      - "traefik.http.routers.react-app.tls.certresolver=letsencrypt-gandi"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
networks:
  default:
  web:
    external: true
